export const actions = {
    CHANGE_APP_STATE: 'CHANGE_APP_STATE',
    UPDATE_ETAGS: 'UPDATE_ETAGS',
    UPDATE_LABELS: 'UPDATE_LABELS',
    UPDATE_ISSUES: 'UPDATE_ISSUES',
    INIT_APP: 'INIT_APP'
};